// Define predetermined views
export const STORE_VIEWS = {
    all: {
        name: 'All Columns',
        description: 'Show all available columns',
        hiddenColumns: [
            'diser_fb_name',
            'diser_company_sv',
            'diser_hold_stop_allow',
            'others_2',
            'others_3',
            'date',
            'dgcage_comment',
            'tshirt_comment',
            'litter_box_comment',
            'pet_bed_comment',
        ]
    },
    fb_list_1: {
        name: 'FB List 1',
        hiddenColumns: [
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'pullout_status',
            'dgcage_status',
            'tshirt_status',
            'litter_box_status',
            'pet_bed_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'diser_hold_stop_allow',
            'others_2',
            'others_3',
            'date',
            'dgcage_comment',
            'tshirt_comment',
            'litter_box_comment',
            'pet_bed_comment',
            'missing_deliveries',
            'items_on_order',
        ],
    },
    fb_list_2: {
        name: 'FB List 2',
        hiddenColumns: [
            'missing_deliveries',
            'items_on_order',
            'pullout_status',
            'dgcage_status',
            'tshirt_status',
            'litter_box_status',
            'pet_bed_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'dgcage_comment',
            'tshirt_comment',
            'litter_box_comment',
            'pet_bed_comment',
            'date',
            'diser_hold_stop_allow',
        ],
    },
    dgcg_ctlltr: {
        name: 'Dgcg & Ctlltr',
        hiddenColumns: [
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'pullout_status',
            'tshirt_status',
            'pet_bed_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'others_2',
            'others_3',
            'date',
            'diser_fb_name',
            'diser_company_sv',
            'diser_hold_stop_allow',
            'pet_bed_comment',
            'tshirt_comment',
            'missing_deliveries',
            'items_on_order',
        ],
    },
    pet_bed: {
        name: 'Pet Bed',
        hiddenColumns: [
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'pullout_status',
            'tshirt_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'others_2',
            'others_3',
            'date',
            'diser_fb_name',
            'diser_company_sv',
            'diser_hold_stop_allow',
            'tshirt_comment',
            'missing_deliveries',
            'items_on_order',
            'dgcage_status',
            'litter_box_status',
            'dgcage_comment',
            'litter_box_comment',
        ],
    },
    tshirt: {
        name: 'Tshirt',
        hiddenColumns: [
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'pullout_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'others_2',
            'others_3',
            'date',
            'diser_fb_name',
            'diser_company_sv',
            'diser_hold_stop_allow',
            'missing_deliveries',
            'items_on_order',
            'dgcage_status',
            'litter_box_status',
            'dgcage_comment',
            'litter_box_comment',
            'pet_bed_status',
            'pet_bed_comment',
        ],
    },
    store_locations: {
        name: 'Store Locations',
        hiddenColumns: [
            'co',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'pullout_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'others_2',
            'others_3',
            'date',
            'diser_fb_name',
            'diser_company_sv',
            'diser_hold_stop_allow',
            'missing_deliveries',
            'items_on_order',
            'dgcage_status',
            'litter_box_status',
            'dgcage_comment',
            'litter_box_comment',
            'pet_bed_status',
            'pet_bed_comment',
            'tshirt_status',
            'tshirt_comment',
        ],
    },
    form_1: {
        name: 'Forms',
        hiddenColumns: [
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'closed',
            'no_diser',
            'class',
            'pullout_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'others_2',
            'others_3',
            'diser_fb_name',
            'diser_company_sv',
            'diser_hold_stop_allow',
            'missing_deliveries',
            'items_on_order',
            'dgcage_status',
            'litter_box_status',
            'dgcage_comment',
            'litter_box_comment',
            'pet_bed_status',
            'pet_bed_comment',
            'tshirt_status',
            'tshirt_comment',
        ],
    },
    submit_inventory: {
        name: 'Submit Inventory',
        hiddenColumns: [
            'co',
            'dc',
            'dr_stamped',
            'area_size',
            'overstock',
            'ratbites',
            'no_diser',
            'pullout_status',
            'gondola_dep',
            'date_depo_refund',
            'po_or_limit',
            'items_not_allowed',
            'items_order',
            'others',
            'others_2',
            'others_3',
            'date',
            'missing_deliveries',
            'items_on_order',
            'dgcage_status',
            'litter_box_status',
            'dgcage_comment',
            'litter_box_comment',
            'pet_bed_status',
            'pet_bed_comment',
            'tshirt_status',
            'tshirt_comment',
        ],
    }
};

// Define predetermined views
export const DISER_VIEWS = {
    all: {
        name: 'All Columns',
        description: 'Show all available columns',
        hiddenColumns: [] as string[],
    },
    diser_computation: {
        name: 'Diser Computation',
        hiddenColumns: ['others_1', 'others_3', 'company_sv'] as string[],
    },
    diser_allowance: {
        name: 'Diser Allowance',
        hiddenColumns: ['others_1', 'others_2', 'others_3', 'sv_only', 'company_sv', 'rsc_re', 'name', 'sales'] as string[],
    },
};